# Generated by Django 4.1.7 on 2023-03-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='www.image.img', max_length=255),
            preserve_default=False,
        ),
    ]
